name: deploy-aws
on: [push]

jobs:
    deploy:
        name: Deploy to AWS
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ secrets.SESSION_TOKEN }}
                  aws-region: us-east-1

            - name: Checkout
              uses: actions/checkout@v2

            - name: Upload to S3
              run: |
                mkdir deployment
                rsync -Rr . deployment
                zip -r deployment.zip deployment
                aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET }}/

            - name: Create deployment
              run: |
                aws deploy create-deployment --application-name teste-vinicius \
                    --deployment-config-name CodeDeployDefault.OneAtATime \
                    --deployment-group-name producao \
                    --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deployment.zip
